services:
  - name: git-scm.com
    type: web
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: git-scm-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: git-scm-db
          property: connectionString
      - fromGroup: git-scm-shared
  - name: git-scm-nightly-job
    type: cron
    env: ruby
    schedule: 0 3 * * *
    buildCommand: bundle install
    startCommand: >
      bundle exec rake preindex
      && bundle exec rake downloads
      && bundle exec rake remote_genbook2
      && bundle exec rake search_index
      && bundle exec rake search_index_book
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: git-scm-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: git-scm-db
          property: connectionString
      - fromGroup: git-scm-shared
  - name: git-scm-redis
    type: redis
    ipAllowList: []

databases:
  - name: git-scm-db
    region: oregon
    plan: basic-256mb
    diskSizeGB: 1

envVarGroups:
  - name: git-scm-shared
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: GITHUB_API_TOKEN
        sync: false
      - key: BONSAI_URL
        sync: false
